### ISSUE TITLE
Promise.resolve(1) throws on Android 4.0

### ISSUE THREAD

**Issue by mzgol** [getify/native-promise-only#43]
`Promise.resolve(1)` throws on Android 4.0:
```
TypeError: Not a promise
  at TypeError (unknown source)
  at new a (http://jquery-master.l/external/npo/npo.js:5:1481)
  at Function.<anonymous> (http://jquery-master.l/external/npo/npo.js:5:2700)
  at http://jquery-master.l/dist/test-promise.html:18:18)
```
This is with `native-promise-only` `0.7.7-a`.
The tested site:
```html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<title>jQuery.when on Android 4.0 test page</title>
</head>
<body>
	<script src="../external/npo/npo.js"></script>
	<div id="result"></div>
	<style>
		#result {
			white-space: pre-wrap;
		}
	</style>
	<script>
		var res;
		try {
			res = Promise.resolve(1);
		} catch (e) {
			res = e.stack || e.message || e;
		}
		document.getElementById('result').textContent = res;
	</script>
</body>
</html>

```

I thought the jQuery test error was related to #38 but it turns out it didn't fix it.

**Comment by getify** [comment]
OK, it appears I did not correctly fix #38 after all. I misunderstood / misremembered. Android 4 doesn't throw an error on setting prototype with OdP, it just silently ignores. :(
